#!/usr/bin/env node
/**
 * Regenerates src/pricing-data.ts from pi's model catalog (@earendil-works/pi-ai), which
 * lists Anthropic list prices in USD per million tokens.
 *
 *   node scripts/update-prices.mjs [path/to/pi-ai/dist/providers/data/anthropic.json]
 *
 * Without an argument, the catalog is located through the globally installed `pi` binary.
 */
import { execFileSync } from "node:child_process";
import { existsSync, readFileSync, realpathSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const here = dirname(fileURLToPath(import.meta.url));
const out = join(here, "..", "src", "pricing-data.ts");

function findCatalog() {
  const bin = realpathSync(execFileSync("which", ["pi"], { encoding: "utf8" }).trim());
  // .../pi-coding-agent/dist/bundle/cli.js -> .../pi-coding-agent
  let dir = dirname(bin);
  while (dir !== dirname(dir) && !existsSync(join(dir, "package.json"))) dir = dirname(dir);
  const candidates = [
    join(dir, "node_modules/@earendil-works/pi-ai/dist/providers/data/anthropic.json"),
    join(dir, "..", "pi-ai/dist/providers/data/anthropic.json"),
  ];
  const found = candidates.find(existsSync);
  if (!found) throw new Error(`Could not find pi's Anthropic catalog near ${dir}; pass its path as an argument.`);
  return found;
}

const file = process.argv[2] ?? findCatalog();
const catalog = JSON.parse(readFileSync(file, "utf8"));
const prices = {};
for (const models of Object.values(catalog)) {
  for (const m of Object.values(models)) {
    if (!m.id?.startsWith("claude-") || !m.cost) continue;
    if (m.cost.tiers?.length) throw new Error(`${m.id} has tiered pricing; teach src/pricing.ts about tiers before updating`);
    const { input, output, cacheRead, cacheWrite } = m.cost;
    prices[m.id] = { input, output, cacheRead, cacheWrite };
  }
}
const ids = Object.keys(prices).sort();
const body = ids.map((id) => `  ${JSON.stringify(id)}: { input: ${prices[id].input}, output: ${prices[id].output}, cacheRead: ${prices[id].cacheRead}, cacheWrite: ${prices[id].cacheWrite} },`).join("\n");
writeFileSync(
  out,
  `// Generated by scripts/update-prices.mjs from pi's model catalog. Do not edit by hand.
// USD per million tokens at Anthropic list price; \`cacheWrite\` is the 5-minute rate (1-hour writes cost 2x \`input\`).

export interface ModelPrice {
  input: number;
  output: number;
  cacheRead: number;
  cacheWrite: number;
}

export const ANTHROPIC_PRICES: Record<string, ModelPrice> = {
${body}
};
`,
);
console.log(`Wrote ${ids.length} models to ${out}`);
